timeout:
  page_timeout: 10000
  action_timeout: 10000

timezone: "Asia/Shanghai"
#timezone: "Etc/UTC"

api_keys:
  openai: sk-1f4ae8888***********************
  deepseek: sk-f4ae8888***********************
  claude: sk-1f4ae8888***********************
  gemini: sk-1f4ae8888***********************

url: https://www.baidu.com